version: "3.3"
   
services:
    ### DJANGO BACKEND-in DJango ###
    webapi:
        build: ./webapi-dj              # Builds the image using the Dockerfile inside ./webapi-dj
        command: python manage.py runserver 0.0.0.0:8001    # Overrides default CMD; starts Django dev server accessible on all interfaces at port 8001
        environment:
          - TRACING_HOST=jaeger
          - TRACING_PORT=6831
        volumes:
          - ./webapi-dj:/webapi         # Mounts local ./webapi-dj folder into the container at /webapi to reflect live code changes
        ports:  
          - "8001:8001"                 # Maps container port 8001 to host port 8001.

    ### OBSERVABILITY APPS ###
    prometheus:
        image: prom/prometheus:v2.35.0    # Uses official Prometheus image, version 2.35.0
        ports:
            - 9090:9090
        volumes:
            - ./prometheus:/etc/prometheus
        command: --config.file=/etc/prometheus/prometheus.yaml

    grafana:
        image: grafana/grafana:8.5.2
        ports:
          - "3000:3000"
        volumes:
          - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
        depends_on:
          - prometheus

    promtail:
        image: grafana/promtail:2.5.0
        volumes:
          - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml
          - ./webapi-dj/webapi.log:/var/log/webapi.log
        command: --config.file=/etc/promtail/promtail.yaml
        depends_on:
          - webapi

    loki:
        image: grafana/loki:2.5.0
        ports:
          - "3100:3100"
        depends_on:
          - promtail

    jaeger:
        image: jaegertracing/all-in-one:1.32
        ports:
          - 16686:16686
          - 6831:6831