version: "1.1"
   
services:
  ### DJANGO BACKEND-in DJango ###
  webapi:
    build: ./webapi-dj
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./webapi-dj:/webapi
    ports:
      - "8001:8001"


  ### OBSERVABILITY APPS ###
  prometheus:
      image: prom/prometheus:v2.35.0
      ports:
          - 9090:9090
      volumes:
          - ./prometheus:/etc/prometheus
      command: --config.file=/etc/prometheus/prometheus.yaml